import Foundation

enum TarotDeck {
    static let allCards: [TarotCard] = majorArcana + cupsCards + wandsCards + swordsCards + pentaclesCards

    // MARK: - Major Arcana (22 cards) — Rider-Waite French names

    static let majorArcana: [TarotCard] = [
        // 0 — Le Fou — Ligne de Vie
        makeMajor(0, "Le Fou",
            ["nouveaux départs", "innocence", "ouverture d'esprit"],
            "Un élan spontané vers l'inconnu. L'innocence et l'ouverture d'esprit ouvrent un chemin inattendu, porté par la foi en la vie.",
            "Négligence et insouciance freinent ta progression. Attention à l'errance sans but et au manque de préparation.",
            love: "En amour, ose la spontanéité sans calcul. Un nouveau départ affectif est possible si tu acceptes de sauter dans le vide.",
            career: "C'est le moment d'un virage audacieux. Une opportunité demande du courage et de la confiance en toi.",
            spiritual: "Un voyage intérieur commence. L'esprit en quête d'expérience est prêt à se laisser guider par la confiance.",
            general: "Le Fou t'invite à embrasser un nouveau départ avec la légèreté de celui qui sait que les anges veillent sur lui.",
            image: "RWS_Tarot_00_Fool",
            numerology: "Vie, égo, conscience"),

        // I — Le Magicien — Ligne de Vie
        makeMajor(1, "Le Magicien",
            ["création", "manifestation", "volonté"],
            "Tu possèdes tous les outils pour créer et manifester ton intention. La volonté consciente transforme le potentiel en réalité.",
            "Blocage créatif ou création guidée par l'ego. Méfie-toi des manipulations et de la dispersion.",
            love: "Tu as le pouvoir de créer la relation que tu désires. Aligne ton intention avec ton cœur.",
            career: "Tes talents sont prêts à être mis en lumière. Habileté et confiance en soi sont tes atouts.",
            spiritual: "Tu es le canal entre le ciel et la terre. Aligne tes pensées pour que le divin se manifeste à travers toi.",
            general: "Le Magicien te rappelle que tu disposes de toutes les ressources. Le moment est venu de transformer l'intention en action.",
            image: "RWS_Tarot_01_Magician",
            numerology: "Une invitation à prendre tes outils, à la magie personnelle, aux capacités infinies"),

        // II — La Grande Prêtresse — Ligne de Vie
        makeMajor(2, "La Grande Prêtresse",
            ["intuition", "mystère", "sagesse cachée"],
            "Les secrets et les mystères t'appellent. Écoute ton intuition profonde avant d'agir, la vérité se révèle dans le silence.",
            "La logique étouffe l'intuition. Résistance au mystère, doute ou superficialité empêchent l'accès à ta sagesse intérieure.",
            love: "L'amour se révèle dans le silence et la patience. Ce qui est caché se dévoilera au moment juste.",
            career: "Observe avant de prendre une décision importante. Le savoir profond guide mieux que la précipitation.",
            spiritual: "La connaissance profonde t'attend dans la méditation. Tu es gardienne d'un savoir sacré qui demande le silence.",
            general: "La Grande Prêtresse t'invite à écouter ton monde intérieur. Ce qui n'est pas encore révélé se manifestera quand tu seras prêt·e.",
            image: "RWS_Tarot_02_High_Priestess",
            numerology: "Dualité, Intuition"),

        // III — L'Impératrice — Ligne de Vie
        makeMajor(3, "L'Impératrice",
            ["réceptivité", "abondance", "énergie féminine"],
            "Réceptivité et abondance s'offrent à toi. Connexion aux cinq sens, fécondité et énergie créatrice nourrissent ta vie.",
            "Lutte avec la réception, esprit de rareté. Tu résistes à l'abondance qui cherche à te parvenir.",
            love: "Une énergie d'amour inconditionnel enveloppe tes relations. Laisse-toi nourrir autant que tu nourris.",
            career: "Un projet créatif est prêt à éclore. L'initiative et la fécondité portent tes entreprises.",
            spiritual: "Connecte-toi à la Terre Mère et à ta nature créatrice. L'Impératrice est le jardin d'Éden terrestre.",
            general: "L'Impératrice t'invite à accueillir l'abondance sous toutes ses formes. Crée, nourris et laisse la vie circuler.",
            image: "RWS_Tarot_03_Empress",
            numerology: "Synthèse, connexion de l'esprit, de l'âme et du corps"),

        // IV — L'Empereur — Ligne de Vie
        makeMajor(4, "L'Empereur",
            ["confiance", "stabilité", "pouvoir"],
            "Impose-toi avec confiance et stabilité. Protection, réalisation et autorité bienveillante structurent ton chemin.",
            "Excès d'autorité ou au contraire timidité. Le pouvoir mal canalisé devient rigidité ou paralysie.",
            love: "Construis des fondations solides dans ta relation. La stabilité naît de l'engagement conscient.",
            career: "Le leadership et l'organisation sont tes atouts. Autorité et volonté portent tes projets.",
            spiritual: "L'ancrage et la discipline structurent ton chemin spirituel. La maîtrise de soi est une forme de souveraineté.",
            general: "L'Empereur t'invite à affirmer ton pouvoir personnel avec sagesse. Stabilise tes bases avec discipline.",
            image: "RWS_Tarot_04_Emperor",
            numerology: "Structure, limites, soins personnels"),

        // V — Le Hiérophante — Ligne de Vie
        makeMajor(5, "L'Hiérophante",
            ["valeurs", "enseignement", "tradition"],
            "Appuie-toi sur une sagesse éprouvée et tes valeurs profondes. L'enseignement juste éclaire le chemin.",
            "Méfiance envers ton propre savoir. Excès de gentillesse ou soumission aveugle à une doctrine limitante.",
            love: "Cherche un amour qui respecte tes valeurs profondes. L'alliance sacrée repose sur des principes partagés.",
            career: "Un mentor ou un enseignement pourrait changer ta perspective. La voie de la sagesse ouvre des portes.",
            spiritual: "La tradition porte des clés, mais ta vérité est unique. Le Hiérophante relie le sacré institué au sacré vécu.",
            general: "Le Hiérophante t'invite à honorer la transmission et les valeurs qui fondent ton parcours.",
            image: "RWS_Tarot_05_Hierophant",
            numerology: "Chrysalide, l'obscurité comme partie de la transformation"),

        // VI — Les Amoureux — Ligne de Vie
        makeMajor(6, "Les Amoureux",
            ["partenariat", "relations", "attraction"],
            "Un choix de cœur se présente. Partenariat, dualité et attraction illuminent ta vie, guidés par l'amour et la beauté.",
            "Solitude, isolement ou conflit intérieur. L'hésitation à s'engager crée frustration et contrariétés.",
            love: "Un choix amoureux majeur se présente. L'amour vrai, libre du désir grossier, éclaire ton chemin.",
            career: "Choisis un chemin professionnel aligné avec tes valeurs. Les épreuves surmontées renforcent ta voie.",
            spiritual: "L'union du cœur et de l'esprit est ta quête. Le mystère de l'amour sacré t'appelle.",
            general: "Les Amoureux t'invitent à un choix fondamental guidé par la cohérence entre ton cœur et tes actes.",
            image: "RWS_Tarot_06_Lovers",
            numerology: "Expansion, créativité, sortie de la chrysalide"),

        // VII — Le Chariot — Ligne de Vie
        makeMajor(7, "Le Chariot",
            ["mouvement", "contrôle", "détermination"],
            "Avance avec détermination vers l'inconnu. Le triomphe de l'esprit, la maîtrise des forces contraires, portent ta conquête.",
            "Tu es coincé·e ou passif·ve. Le manque de direction ou les querelles intérieures ralentissent ta progression.",
            love: "L'amour avance quand tu prends les rênes avec confiance et détermination.",
            career: "Le succès est proche. La victoire appartient à celui qui maîtrise ses forces intérieures.",
            spiritual: "Maîtrise tes forces intérieures pour avancer. Le Chariot est le triomphe de l'esprit sur la matière.",
            general: "Le Chariot t'invite à avancer avec détermination. La conquête vient de la maîtrise, pas de la force brute.",
            image: "RWS_Tarot_07_Chariot",
            numerology: "Travail intérieur"),

        // VIII — La Force — Ligne de Mort
        makeMajor(8, "La Force",
            ["force intérieure", "courage", "magnanimité"],
            "La vraie puissance naît de la douceur intérieure. Courage, énergie et magnanimité te mènent au succès véritable.",
            "Posture défensive ou doute profond. L'abus de pouvoir ou la faiblesse signalent un déséquilibre.",
            love: "La douceur et la patience apprivoisent les cœurs. L'amour vrai se nourrit de force tranquille.",
            career: "Ta résilience est ton plus grand atout. L'énergie et l'action portent tes ambitions.",
            spiritual: "La maîtrise de soi est le plus haut degré de force. La chaîne de fleurs dompte le lion.",
            general: "La Force t'invite à puiser dans ta puissance intérieure avec douceur. Le lion se soumet à la compassion, jamais à la violence.",
            image: "RWS_Tarot_08_Strength",
            numerology: "Transformation, mouvement"),

        // IX — L'Ermite — Ligne de Mort
        makeMajor(9, "L'Ermite",
            ["écoute intérieure", "prudence", "discernement"],
            "Écoute à l'intérieur de toi. La prudence et le discernement guident ta lanterne vers la vérité cachée.",
            "Isolement, solitude ou dissimulation. La peur ou la prudence excessive te coupent du monde.",
            love: "Parfois, il faut être seul·e pour mieux comprendre ce que tu cherches dans l'autre.",
            career: "Le retrait stratégique nourrit une vision plus claire. La circumspection protège des faux pas.",
            spiritual: "La solitude est un sanctuaire pour l'âme qui cherche. L'Ermite porte la lumière pour ceux qui suivent.",
            general: "L'Ermite t'invite à chercher la vérité dans le silence. Son phare indique : là où je suis, tu peux aussi être.",
            image: "RWS_Tarot_09_Hermit",
            numerology: "Intégration des enseignements tirés des autres numéros"),

        // X — La Roue de Fortune — Ligne de Mort
        makeMajor(10, "La Roue de Fortune",
            ["changement", "cycles", "destinée"],
            "Un tournant majeur s'ouvre. Les cycles de la destinée tournent, apportant fortune, élévation et chance.",
            "Tu cherches à tout contrôler. Résistance aux cycles naturels et au mouvement inévitable de la vie.",
            love: "Les cycles de l'amour tournent, accueille ce qui vient. La roue n'épargne personne.",
            career: "Un changement inattendu ouvre de nouvelles portes. La fortune sourit à celui qui s'adapte.",
            spiritual: "Tout est cyclique, fais confiance au mouvement de la vie. La Providence est impliquée en toute chose.",
            general: "La Roue de Fortune te rappelle que rien n'est permanent. Le hasard et la fatalité n'existent pas, seul le mouvement sacré opère.",
            image: "RWS_Tarot_10_Wheel_of_Fortune",
            numerology: "Achèvement et nouveau commencement"),

        // XI — La Justice — Ligne de Mort
        makeMajor(11, "La Justice",
            ["vérité", "harmonie", "équité"],
            "La vérité et l'harmonie réclament leur dû. Équité, probité et triomphe du côté méritant guident ta route.",
            "Malhonnêteté ou injustice. Les préjugés et la sévérité excessive déséquilibrent la balance.",
            love: "L'honnêteté est le socle d'une relation saine. La Justice rend à chacun ce qui lui revient.",
            career: "Un contrat ou une décision légale demande ton attention. Le droit et l'équité prévalent.",
            spiritual: "Le karma agit, aligne-toi avec ta conscience. La Justice spirituelle diffère de la justice mondaine.",
            general: "La Justice t'invite à choisir la clarté et l'intégrité. Ce qui est juste prévaudra.",
            image: "RWS_Tarot_11_Justice",
            numerology: "Dualité, Intuition"),

        // XII — Le Pendu — Ligne de Mort
        makeMajor(12, "Le Pendu",
            ["lâcher-prise", "sagesse", "sacrifice"],
            "Lâcher prise ouvre une perspective nouvelle. Sagesse, discernement et sacrifice conscient révèlent ce qui était caché.",
            "Tu t'accroches à ce qui devrait être libéré. L'égoïsme ou le refus du changement bloquent ta progression.",
            love: "Lâcher le contrôle permet à l'amour de circuler. Le sacrifice amoureux porte ses fruits.",
            career: "Voir les choses sous un nouvel angle change tout. La suspension temporaire mène à l'illumination.",
            spiritual: "Le sacrifice conscient mène à la résurrection. Après le mystère de la mort, vient la gloire du renouveau.",
            general: "Le Pendu t'invite à suspendre l'action pour trouver la sagesse. Ce qui semble une impasse est une porte dérobée.",
            image: "RWS_Tarot_12_Hanged_Man",
            numerology: "Synthèse, connexion de l'esprit, de l'âme et du corps"),

        // XIII — La Mort — Ligne de Mort
        makeMajor(13, "La Mort",
            ["métamorphose", "transformation", "fin"],
            "Une métamorphose profonde est en cours. La fin d'un cycle ancien prépare le terrain d'une renaissance inévitable.",
            "Stagnation et peur du changement. Tu refuses la transformation, ce qui prolonge une agonie inutile.",
            love: "Une relation se transforme profondément. Laisse mourir ce qui ne sert plus pour renaître ensemble.",
            career: "La fin d'un cycle professionnel annonce un renouveau. La destruction précède toujours la création.",
            spiritual: "Meurs à l'ancien pour renaître. La mort mystique n'est pas une fin, c'est un passage vers la lumière.",
            general: "La Mort t'invite à accueillir la transformation sans crainte. Le cavalier avance lentement, portant la rose de la vie.",
            image: "RWS_Tarot_13_Death",
            numerology: "Structure, limites, soins personnels"),

        // XIV — La Tempérance — Ligne de Mort
        makeMajor(14, "La Tempérance",
            ["équilibre", "modération", "alchimie"],
            "L'équilibre et la modération harmonisent les contraires. L'ange verse les essences de la vie d'un calice à l'autre.",
            "Manque d'équilibre et extrêmes. Les excès dans un sens ou l'autre provoquent désunion et chaos.",
            love: "L'équilibre entre donner et recevoir nourrit l'amour. La tempérance harmonise le psychique et le matériel.",
            career: "La patience et la mesure portent des fruits durables. L'économie de moyens assure le succès.",
            spiritual: "L'alchimie intérieure opère dans la douceur. Sous cette règle, tu sais d'où tu viens et où tu vas.",
            general: "La Tempérance t'invite à trouver le juste milieu. Elle combine et harmonise les natures psychique et matérielle.",
            image: "RWS_Tarot_14_Temperance",
            numerology: "Chrysalide, l'obscurité comme partie de la transformation"),

        // XV — Le Diable — Spirale de Renaissance
        makeMajor(15, "Le Diable",
            ["rébellion", "liberté", "chaînes"],
            "La rébellion et la liberté t'appellent. Cette carte révèle les chaînes que tu portes, mais aussi la force de les briser.",
            "Rigidité et fatalisme. Les chaînes semblent inévitables, mais c'est l'aveuglement qui empêche de voir la sortie.",
            love: "Distingue le désir de l'amour véritable. Les attachements toxiques peuvent être défaits.",
            career: "Ne laisse pas l'ambition te couper de tes valeurs. La force et la véhémence doivent servir un but juste.",
            spiritual: "Confronte ton ombre pour intégrer ta pleine lumière. L'habitant du seuil garde l'entrée du jardin mystique.",
            general: "Le Diable te montre ce qui t'enchaîne. Les chaînes sont plus lâches qu'elles n'y paraissent. La libération commence par la conscience.",
            image: "RWS_Tarot_15_Devil",
            numerology: "Expansion, créativité, sortie de la chrysalide"),

        // XVI — La Tour — Spirale de Renaissance
        makeMajor(16, "La Tour",
            ["défaillance structurelle", "catastrophe", "révélation"],
            "Ce qui est bâti sur de fausses fondations s'effondre. La catastrophe libère et révèle la vérité sous les décombres.",
            "Résistance au changement nécessaire. L'oppression et la tyrannie s'accrochent aux ruines.",
            love: "Un bouleversement libère de faux semblants. La vérité nue est le seul socle d'un amour durable.",
            career: "Une rupture professionnelle inattendue est un cadeau déguisé. La Tour qui tombe libère.",
            spiritual: "L'ego s'effondre pour laisser place à la vérité. La ruine de la Maison de la fausse doctrine ouvre le ciel.",
            general: "La Tour t'annonce un effondrement nécessaire. Si le Seigneur ne bâtit la maison, ceux qui la bâtissent travaillent en vain.",
            image: "RWS_Tarot_16_Tower",
            numerology: "Travail intérieur"),

        // XVII — L'Étoile — Spirale de Renaissance
        makeMajor(17, "L'Étoile",
            ["espoir", "guérison", "renouveau"],
            "L'espoir renaît après la tempête. Guérison et renouveau coulent comme les eaux de la vie, offertes à qui sait les recevoir.",
            "Refus de la guérison ou surproductivité. L'arrogance empêche de recevoir les dons de l'Esprit.",
            love: "L'amour vrai brille déjà dans ta vie. La Vérité dévoilée se donne dans sa beauté éternelle.",
            career: "L'inspiration guide tes projets vers le succès. Eaux de vie gratuites et dons de l'Esprit nourrissent ton œuvre.",
            spiritual: "Tu es connecté·e à une guidance céleste. L'Étoile est la Grande Mère qui communique sa lumière aux mondes inférieurs.",
            general: "L'Étoile t'invite à accueillir la guérison et l'espoir. Après la destruction de la Tour, la lumière revient.",
            image: "RWS_Tarot_17_Star",
            numerology: "Transformation, mouvement"),

        // XVIII — La Lune — Spirale de Renaissance
        makeMajor(18, "La Lune",
            ["illusion", "subconscient", "peurs"],
            "L'illusion et le subconscient dominent. Les forces cachées, les peurs et les rêves réclament ton attention.",
            "Confusion ou excès de clarté forcée. L'instabilité et l'inconstance brouillent ta perception.",
            love: "Les émotions profondes éclairent tes vrais besoins affectifs. Méfie-toi des illusions sentimentales.",
            career: "Fie-toi à ton intuition plutôt qu'aux apparences. Les ennemis cachés se révèlent à la lumière lunaire.",
            spiritual: "Les rêves et l'imaginaire portent des messages sacrés. La lumière réfléchie éclaire la nature animale.",
            general: "La Lune t'invite à traverser tes peurs. Le chemin entre les tours est la sortie vers l'inconnu.",
            image: "RWS_Tarot_18_Moon",
            numerology: "Intégration des enseignements tirés des autres numéros"),

        // XIX — Le Soleil — Spirale de Renaissance
        makeMajor(19, "Le Soleil",
            ["célébration", "bonheur", "visibilité"],
            "Laisse-toi voir et célèbre la vie. Le bonheur matériel, la joie partagée et la lumière intérieure rayonnent.",
            "Tu te caches ou tu n'es pas tout à fait prêt·e à célébrer. La lumière semble trop forte.",
            love: "La joie et la clarté illuminent tes relations. Un mariage heureux ou un amour lumineux se profile.",
            career: "Un succès éclatant se profile. Le contentement et la réalisation couronnent tes efforts.",
            spiritual: "Ta lumière intérieure rayonne et inspire les autres. L'esprit de connaissance de soi est apparu.",
            general: "Le Soleil t'invite à rayonner pleinement. La lumière directe, antithèse du reflet, éclaire tout ce qu'elle touche.",
            image: "RWS_Tarot_19_Sun",
            numerology: "Une invitation à prendre tes outils, à la magie personnelle"),

        // XX — Le Jugement — Spirale de Renaissance
        makeMajor(20, "Le Jugement",
            ["éveil", "renouvellement", "appel"],
            "Un appel profond résonne en toi. L'éveil et le renouvellement transforment ta position dans le monde.",
            "Tu restes coincé·e dans le passé. La faiblesse et l'indécision empêchent de répondre à l'appel.",
            love: "Un appel profond transforme ta vision de l'amour. Les morts sortent de leurs tombes, un cycle s'achève.",
            career: "Un changement radical s'impose. Le renouvellement de ta position est en cours.",
            spiritual: "L'éveil de conscience te libère des anciens schémas. La grande œuvre de transformation s'accomplit.",
            general: "Le Jugement t'invite à répondre à l'appel de ton âme. La trompette sonne et tout ce qui est inférieur en toi s'élève.",
            image: "RWS_Tarot_20_Judgement",
            numerology: "Dualité, Intuition"),

        // XXI — Le Monde — Spirale de Renaissance
        makeMajor(21, "Le Monde",
            ["achèvement", "accomplissement", "récompense"],
            "Le cycle est accompli. Succès assuré, récompense méritée, le voyage touche à sa fin et un nouveau monde s'ouvre.",
            "Il manque des pièces pour l'achèvement. L'inertie ou la stagnation empêchent la clôture du cycle.",
            love: "L'amour atteint un palier de plénitude et d'harmonie. La perfection de l'amitié et de l'amour humain.",
            career: "Un accomplissement majeur couronne tes efforts. Le succès assuré et la récompense sont à portée.",
            spiritual: "Tu as intégré une leçon fondamentale. Le Monde représente la perfection du Cosmos qui se comprend en Dieu.",
            general: "Le Monde t'annonce la fin glorieuse d'un cycle. Tout a été déclaré bon, un nouveau voyage commence.",
            image: "RWS_Tarot_21_World",
            numerology: "Synthèse, connexion de l'esprit, de l'âme et du corps")
    ]

    // MARK: - Coupes (Cups) — 💧 Eau (14 cards)

    static let cupsCards: [TarotCard] = [

        // As de Coupes
        makeMinor(1, "As de Coupes",
            suit: .cups,
            keywords: ["joie", "abondance", "contentement"],
            upright: "Une source d'amour pur jaillit dans ta vie. Le coeur vrai s'ouvre à la joie, au contentement et à une abondance émotionnelle qui nourrit l'âme en profondeur.",
            reversed: "Les émotions sont bloquées, comme une source tarie. Le faux coeur s'installe, portant instabilité et mutation intérieure qui empêchent la joie de circuler librement.",
            love: "Un nouvel amour ou un renouveau émotionnel profond s'offre à toi, porté par la tendresse et la fertilité du coeur.",
            career: "Une opportunité nourricière se présente, porteuse de satisfaction profonde et d'abondance dans ton travail.",
            spiritual: "La coupe divine déborde de grâce ; ouvre ton coeur pour recevoir cette nourriture sacrée qui t'est destinée.",
            general: "L'As de Coupes t'invite à honorer tes émotions et à accueillir la plénitude qui frappe à la porte de ton coeur.",
            image: "Cups01",
            element: "💧 Eau",
            numerology: "Une invitation à prendre vos outils, à la magie personnelle"),

        // Deux de Coupes
        makeMinor(2, "Deux de Coupes",
            suit: .cups,
            keywords: ["partenariat", "union", "amour"],
            upright: "Un lien profond se tisse entre deux âmes. L'amour, la passion et l'affinité créent une union harmonieuse où la sympathie et la concorde règnent en maîtresses.",
            reversed: "Le rejet de soi ou de l'autre crée une fracture. La dysharmonie et la méfiance s'installent, fragilisant les liens qui demandaient pourtant à fleurir.",
            love: "Une connexion amoureuse authentique se révèle, fondée sur l'amitié profonde et la réciprocité des sentiments.",
            career: "Un partenariat professionnel prometteur se dessine, bâti sur la confiance mutuelle et l'affinité naturelle.",
            spiritual: "L'amour de soi est la première coupe à remplir ; de cette source intérieure naît la capacité d'aimer véritablement l'autre.",
            general: "Le Deux de Coupes célèbre l'union sacrée des coeurs et t'invite à cultiver l'harmonie dans toutes tes relations.",
            image: "Cups02",
            element: "💧 Eau",
            numerology: "Dualité, Intuition"),

        // Trois de Coupes
        makeMinor(3, "Trois de Coupes",
            suit: .cups,
            keywords: ["communauté", "célébration", "abondance"],
            upright: "La joie se partage et se multiplie au sein de ta communauté. Victoire, accomplissement et réconfort couronnent une affaire menée dans l'abondance et la gaieté.",
            reversed: "L'isolement te coupe de la chaleur des autres, ou bien la dépendance excessive envers le groupe t'éloigne de toi-même. Les excès de jouissance obscurcissent le vrai plaisir.",
            love: "L'amour s'épanouit dans la joie partagée et les cercles bienveillants qui célèbrent votre union.",
            career: "Le travail d'équipe porte ses fruits dans l'abondance ; la collaboration joyeuse mène à la réussite collective.",
            spiritual: "L'esprit, l'âme et le corps se rejoignent dans une danse sacrée de guérison et de plénitude.",
            general: "Le Trois de Coupes t'invite à célébrer avec ceux qui te soutiennent et à goûter la perfection de l'instant partagé.",
            image: "Cups03",
            element: "💧 Eau",
            numerology: "Synthèse, connexion de l'esprit, de l'âme et du corps"),

        // Quatre de Coupes
        makeMinor(4, "Quatre de Coupes",
            suit: .cups,
            keywords: ["méditation", "délibération", "limites"],
            upright: "Un temps de retrait et de délibération s'impose. La méditation révèle que la lassitude cache parfois un appel à poser des limites émotionnelles claires et bienveillantes.",
            reversed: "Tu prends sur tes épaules des fardeaux qui ne t'appartiennent pas. Pourtant, de nouvelles relations et de nouvelles perspectives attendent que tu lèves les yeux.",
            love: "Prends le temps de contempler ce que tu désires vraiment en amour avant d'accepter ou de refuser ce qui t'est offert.",
            career: "La lassitude professionnelle invite à la réflexion ; une pause consciente peut révéler des opportunités insoupçonnées.",
            spiritual: "Les limites que tu poses sont un acte sacré de soin personnel ; la méditation t'ouvre les portes d'une perception renouvelée.",
            general: "Le Quatre de Coupes te demande de faire le tri dans tes émotions et de discerner ce qui mérite vraiment ton attention.",
            image: "Cups04",
            element: "💧 Eau",
            numerology: "Structure, limites, soins personnels"),

        // Cinq de Coupes
        makeMinor(5, "Cinq de Coupes",
            suit: .cups,
            keywords: ["chagrin", "perte", "transmission"],
            upright: "Le chagrin voile ton regard, mais derrière la perte se cache un héritage précieux. Ce qui t'est transmis ne correspond pas toujours à tes attentes, et l'amertume colore l'expérience.",
            reversed: "Le temps du lâcher-prise est venu. L'acceptation et le pardon ouvrent la voie à de nouvelles alliances, à un retour vers la lumière que tu croyais perdue.",
            love: "Le deuil d'un amour ou d'une illusion libère l'espace pour une affection plus authentique et plus profonde.",
            career: "Un héritage professionnel ou une transition inattendue demande d'accepter la frustration pour mieux renaître.",
            spiritual: "L'obscurité fait partie de la transformation ; comme la chrysalide, le chagrin prépare la métamorphose de l'âme.",
            general: "Le Cinq de Coupes t'invite à retourner ton regard vers les coupes encore debout et à trouver la grâce dans ce qui reste.",
            image: "Cups05",
            element: "💧 Eau",
            numerology: "Chrysalide, l'obscurité comme partie de la transformation"),

        // Six de Coupes
        makeMinor(6, "Six de Coupes",
            suit: .cups,
            keywords: ["nostalgie", "souvenirs", "innocence"],
            upright: "Les souvenirs du passé reviennent comme un parfum d'enfance. Le bonheur venu d'autrefois éclaire le présent, tandis que de nouvelles relations fleurissent dans un environnement renouvelé.",
            reversed: "Tu restes prisonnier d'un passé qui ne te sert plus. Pourtant, l'avenir et le renouveau frappent à ta porte, prêts à se réaliser dans l'immédiat.",
            love: "Un amour teinté de nostalgie et d'innocence revient ou bien un nouveau lien rappelle la douceur des premiers émois.",
            career: "Un ancien projet ou un contact du passé refait surface et porte en lui les graines d'un nouveau départ professionnel.",
            spiritual: "Retrouve l'émerveillement de l'enfant intérieur ; la créativité sacrée naît de cette connexion à l'innocence originelle.",
            general: "Le Six de Coupes t'invite à honorer tes racines tout en accueillant les promesses du renouveau qui se dessine.",
            image: "Cups06",
            element: "💧 Eau",
            numerology: "Expansion, créativité, sortie de la chrysalide"),

        // Sept de Coupes
        makeMinor(7, "Sept de Coupes",
            suit: .cups,
            keywords: ["imagination", "illusions", "rêverie"],
            upright: "Les faveurs des fées scintillent devant toi, images de la réflexion et de l'imagination. Une certaine réussite se dessine, mais rien de permanent ni de substantiel ne se construit sur les seuls rêves.",
            reversed: "Tu te perds dans la rêverie au point d'oublier le réel. Pourtant, le désir et la volonté demandent à se transformer en projet concret et en détermination.",
            love: "Distingue le fantasme amoureux de la réalité du coeur ; les illusions sentimentales doivent céder la place à un amour ancré.",
            career: "Les visions professionnelles abondent, mais il est temps de choisir un seul chemin et de t'y engager pleinement.",
            spiritual: "Le travail intérieur consiste à discerner les mirages de l'ego des véritables visions de l'âme.",
            general: "Le Sept de Coupes t'invite à sortir du brouillard enchanté pour ancrer tes rêves les plus chers dans la réalité.",
            image: "Cups07",
            element: "💧 Eau",
            numerology: "Travail intérieur"),

        // Huit de Coupes
        makeMinor(8, "Huit de Coupes",
            suit: .cups,
            keywords: ["lâcher-prise", "départ", "liberté"],
            upright: "Le moment est venu de partir vers l'inconnu. Ce que tu croyais important révèle sa faible importance, et le lâcher-prise ouvre un chemin de liberté et de renouveau.",
            reversed: "Tu t'accroches à ce qui devrait être libéré, par peur du vide ou de l'inconnu. Pourtant, la joie et le bonheur t'attendent au-delà de cet attachement.",
            love: "Quitter une relation ou un schéma amoureux qui ne te nourrit plus est un acte de courage et d'amour envers toi-même.",
            career: "Un départ professionnel, même douloureux, ouvre la voie à une vocation plus alignée avec ta vérité.",
            spiritual: "La transformation passe par l'abandon conscient de ce qui a fait son temps ; chaque pas vers l'inconnu est un pas vers le sacré.",
            general: "Le Huit de Coupes t'invite à tourner le dos à ce qui ne te sert plus et à marcher sous la lune vers ta prochaine métamorphose.",
            image: "Cups08",
            element: "💧 Eau",
            numerology: "Transformation, mouvement"),

        // Neuf de Coupes
        makeMinor(9, "Neuf de Coupes",
            suit: .cups,
            keywords: ["satisfaction", "voeux", "bien-être"],
            upright: "Tes voeux les plus chers se réalisent. La concorde, le contentement et le bien-être physique t'enveloppent ; victoire, succès et satisfaction couronnent tes efforts.",
            reversed: "Tu résistes à tes propres désirs par peur de les mériter. La vérité et la loyauté t'appellent, mais les imperfections te font douter de ton droit au bonheur.",
            love: "L'amour comble tes attentes les plus profondes ; savoure cette plénitude sentimentale sans culpabilité.",
            career: "Le succès professionnel et la reconnaissance sont au rendez-vous ; tes efforts portent enfin leurs fruits abondants.",
            spiritual: "Écoute tes désirs les plus profonds, car ils sont la voix de ton âme qui connaît le chemin de ta plénitude.",
            general: "Le Neuf de Coupes t'invite à accueillir la satisfaction et à croire que tu mérites chaque bénédiction qui se présente.",
            image: "Cups09",
            element: "💧 Eau",
            numerology: "Intégration des enseignements tirés des autres numéros"),

        // Dix de Coupes
        makeMinor(10, "Dix de Coupes",
            suit: .cups,
            keywords: ["bonheur", "harmonie", "alignement"],
            upright: "Le bonheur véritable illumine ta vie. Le repos du coeur tout entier s'installe dans la perfection de l'amour et de l'amitié humaine, un alignement profond entre tes rêves et ta réalité.",
            reversed: "Un désalignement trouble la paix intérieure. Le repos du faux coeur masque une indignation ou une violence sourde qui demande à être reconnue et guérie.",
            love: "L'amour familial et romantique atteint un sommet de plénitude ; le foyer rayonne de tendresse et d'harmonie partagée.",
            career: "L'épanouissement professionnel s'accompagne d'un profond sentiment de contentement et de paix intérieure.",
            spiritual: "L'arc-en-ciel de la promesse divine brille au-dessus de toi ; ton âme a trouvé son foyer sacré.",
            general: "Le Dix de Coupes t'annonce la perfection d'un cycle émotionnel accompli et la bénédiction d'un bonheur partagé.",
            image: "Cups10",
            element: "💧 Eau",
            numerology: "Achèvement"),

        // Valet de Coupes
        makeMinor(11, "Valet de Coupes",
            suit: .cups,
            keywords: ["rêveur", "créativité", "message"],
            upright: "Un jeune rêveur porte un message du coeur. Studieux et contemplatif, il invite à la réflexion, à la méditation et à l'expression créative de tes émotions les plus délicates.",
            reversed: "L'immaturité émotionnelle brouille le message intérieur. Le goût pour la séduction et l'artifice risque de te détourner de la sincérité que ton coeur réclame.",
            love: "Un message amoureux ou une nouvelle rencontre éveille en toi une sensibilité créative et une tendresse inattendue.",
            career: "Une idée créative ou une proposition inattendue mérite toute ton attention et ta réflexion approfondie.",
            spiritual: "Cultive l'émerveillement du débutant ; la méditation et l'application ouvrent les portes de la vision intérieure.",
            general: "Le Valet de Coupes t'invite à accueillir les messages subtils de ton coeur avec la curiosité d'un jeune étudiant de l'âme.",
            image: "Cups11",
            element: "💧 Eau",
            numerology: "Racines/Fondations"),

        // Cavalier de Coupes
        makeMinor(12, "Cavalier de Coupes",
            suit: .cups,
            keywords: ["romantisme", "invitation", "quête"],
            upright: "Un chevalier du coeur s'avance, porteur d'une invitation ou d'une proposition sincère. Suivre son coeur avec grâce et détermination ouvre des chemins insoupçonnés.",
            reversed: "Le coeur est questionné par le doute. Derrière les belles paroles peuvent se cacher tromperie, artifice et duplicité qui demandent ton discernement.",
            love: "Une proposition romantique ou une avance sincère arrive dans ta vie ; laisse ton coeur guider ta réponse.",
            career: "Une opportunité se présente avec élégance ; suis ton intuition pour évaluer si cette invitation est alignée avec tes valeurs.",
            spiritual: "Le chevalier t'invite à suivre le courant de tes émotions les plus pures comme un fleuve qui rejoint l'océan.",
            general: "Le Cavalier de Coupes t'encourage à suivre l'appel de ton coeur avec la noblesse de celui qui chevauche vers sa vérité.",
            image: "Cups12",
            element: "💧 Eau",
            numerology: "Mouvement"),

        // Reine de Coupes
        makeMinor(13, "Reine de Coupes",
            suit: .cups,
            keywords: ["compassion", "intuition", "sagesse"],
            upright: "La Reine de Coupes incarne la compassion et l'amour dans leur forme la plus pure. Belle et dévouée, elle porte le don de vision, la sagesse du coeur et une intelligence aimante qui guérit.",
            reversed: "La co-dépendance étouffe l'amour véritable. L'excès de dévotion envers les autres te fait perdre ta propre lumière, et la confiance mal placée mène au déshonneur.",
            love: "Un amour profond, maternel et inconditionnel enveloppe ta vie sentimentale de sa grâce bienveillante.",
            career: "Ton intelligence émotionnelle et ta capacité d'écoute sont tes plus grands atouts professionnels.",
            spiritual: "La Reine porte la coupe de la vision sacrée ; ta compassion est le vaisseau par lequel le divin se manifeste.",
            general: "La Reine de Coupes t'invite à embrasser ta sensibilité comme un don et à laisser ta sagesse intuitive éclairer le chemin des autres.",
            image: "Cups13",
            element: "💧 Eau",
            numerology: "Travail Intérieur"),

        // Roi de Coupes
        makeMinor(14, "Roi de Coupes",
            suit: .cups,
            keywords: ["intelligence émotionnelle", "équité", "maîtrise"],
            upright: "Le Roi de Coupes règne par l'intelligence émotionnelle et la créativité. Homme juste et responsable, il incarne l'équité, l'art et la science du coeur avec une maîtrise bienveillante.",
            reversed: "La manipulation émotionnelle empoisonne les relations. Derrière le masque d'un homme à double jeu se cachent l'injustice, le vice et le scandale qui appellent la vigilance.",
            love: "Un amour mature et équilibré, guidé par la sagesse émotionnelle et l'engagement responsable, se manifeste dans ta vie.",
            career: "Ta créativité et ton intelligence relationnelle font de toi un leader respecté et inspirant dans ton domaine.",
            spiritual: "La maîtrise des émotions est la couronne du roi intérieur ; gouverne ton monde avec le sceptre de la compassion éclairée.",
            general: "Le Roi de Coupes t'invite à régner sur tes émotions avec sagesse et à mettre ton intelligence créatrice au service du bien commun.",
            image: "Cups14",
            element: "💧 Eau",
            numerology: "Concrétisation"),
    ]

    // MARK: - Bâtons (Wands) — 🔥 Feu (14 cards)

    static let wandsCards: [TarotCard] = [
// As de Bâtons
        makeMinor(1, "As de Bâtons",
            suit: .wands,
            keywords: ["création", "énergie", "commencement"],
            upright: "Une étincelle puissante de créativité s'éveille en vous, porteuse d'un élan nouveau. C'est le moment de créer, d'inventer et d'entreprendre avec audace. La source de toute inspiration jaillit, annonçant une naissance lumineuse.",
            reversed: "Votre énergie créatrice peine à trouver son chemin et se disperse en vain. Une certaine joie trouble masque un sentiment de décadence intérieure. Prenez garde à ne pas gaspiller ce feu sacré qui brûle sans direction.",
            love: "Une passion nouvelle s'embrase, porteuse de promesses et de désirs ardents.",
            career: "Un projet audacieux prend forme, nourri par votre créativité et votre détermination.",
            spiritual: "Saisissez vos outils intérieurs et éveillez la magie personnelle qui sommeille en vous.",
            general: "Le feu créateur s'offre à vous comme une invitation à bâtir quelque chose de grand et de neuf.",
            image: "Wands01",
            element: "🔥 Feu",
            numerology: "Une invitation à prendre vos outils, à la magie personnelle"),

        // Deux de Bâtons
        makeMinor(2, "Deux de Bâtons",
            suit: .wands,
            keywords: ["préparation", "décision", "vision"],
            upright: "Vous contemplez l'horizon depuis une position de force, prêt à choisir votre voie. Les décisions qui se présentent portent en elles la promesse de richesse et de grandeur. Tel un seigneur surplombant ses terres, vous tenez le monde entre vos mains.",
            reversed: "La procrastination vous retient au seuil de l'aventure, ou bien vous vous lancez sans y être préparé. Surprise et émerveillement se mêlent à un trouble profond. La peur de l'inconnu paralyse votre élan naturel.",
            love: "Une décision importante se profile dans votre vie sentimentale, ouvrant la porte à de nouveaux horizons.",
            career: "Vous planifiez avec ambition votre prochaine étape professionnelle depuis une position avantageuse.",
            spiritual: "La dualité entre rester et partir vous invite à écouter votre intuition la plus profonde.",
            general: "Le moment est venu de regarder au-delà du connu et de préparer votre expansion vers de nouveaux territoires.",
            image: "Wands02",
            element: "🔥 Feu",
            numerology: "Dualité, Intuition"),

        // Trois de Bâtons
        makeMinor(3, "Trois de Bâtons",
            suit: .wands,
            keywords: ["expansion", "entreprise", "coopération"],
            upright: "Vos efforts portent leurs fruits et l'expansion tant attendue se dessine à l'horizon. Le commerce et la découverte ouvrent des voies nouvelles, comme des navires chargés de richesses. La coopération se révèle efficace et vos entreprises prospèrent.",
            reversed: "Des obstacles freinent votre progression et mettent votre patience à l'épreuve. Pourtant, cette pause annonce aussi la fin des ennuis et la cessation de l'adversité. La déception s'efface doucement pour laisser place à un renouveau.",
            love: "Votre relation s'épanouit et s'ouvre à de belles perspectives communes, pleines de promesses partagées.",
            career: "Vos projets professionnels prennent de l'envergure grâce à des collaborations fructueuses et bien établies.",
            spiritual: "L'esprit, l'âme et le corps trouvent leur synthèse dans une connexion harmonieuse et profonde.",
            general: "Les fondations sont posées et le vent favorable pousse vos ambitions vers des terres promises.",
            image: "Wands03",
            element: "🔥 Feu",
            numerology: "Synthèse, connexion de l'esprit, de l'âme et du corps"),

        // Quatre de Bâtons
        makeMinor(4, "Quatre de Bâtons",
            suit: .wands,
            keywords: ["célébration", "harmonie", "foyer"],
            upright: "La joie et la célébration illuminent votre quotidien dans une atmosphère de paix et de concorde. Vous vous sentez profondément bien dans votre peau, ancré dans un foyer chaleureux et accueillant. La prospérité et l'harmonie règnent, offrant un repos bien mérité.",
            reversed: "Un manque de soutien assombrit la fête, mais la prospérité demeure malgré tout. La beauté et la félicité continuent de croître, même si elles passent inaperçues. Cherchez en vous-même le refuge que le monde extérieur peine à vous offrir.",
            love: "Votre union rayonne de bonheur et d'harmonie, comme une fête qui ne demande qu'à durer.",
            career: "Vos réussites professionnelles méritent d'être célébrées dans un esprit de gratitude et de partage.",
            spiritual: "Prenez soin de vous et honorez la structure sacrée de votre temple intérieur.",
            general: "Un moment béni de paix domestique et de récolte heureuse enveloppe votre vie de douceur.",
            image: "Wands04",
            element: "🔥 Feu",
            numerology: "Structure, limites, soins personnels"),

        // Cinq de Bâtons
        makeMinor(5, "Cinq de Bâtons",
            suit: .wands,
            keywords: ["conflit", "compétition", "défi"],
            upright: "La compétition fait rage autour de vous, mêlant combat simulé et lutte acharnée pour la réussite. Les rivalités s'expriment avec vigueur dans cette bataille inévitable de la vie. Chaque défi rencontré forge votre caractère et révèle votre force intérieure.",
            reversed: "Vous émergez enfin du conflit, mais la passivité guette au tournant. Les litiges et contradictions s'apaisent lentement, laissant place à une trêve fragile. Méfiez-vous des ruses et des contestations qui couvent encore sous la surface.",
            love: "Des désaccords passionnés agitent votre relation, mais cette friction peut aussi raviver la flamme.",
            career: "La concurrence professionnelle vous pousse à donner le meilleur de vous-même et à vous surpasser.",
            spiritual: "L'obscurité fait partie de la transformation, comme la chrysalide prépare l'envol du papillon.",
            general: "Les tensions actuelles sont le creuset dans lequel se forge une version plus forte et plus sage de vous-même.",
            image: "Wands05",
            element: "🔥 Feu",
            numerology: "Chrysalide, l'obscurité comme partie de la transformation"),

        // Six de Bâtons
        makeMinor(6, "Six de Bâtons",
            suit: .wands,
            keywords: ["reconnaissance", "victoire", "progrès"],
            upright: "Le triomphe vous couronne et la reconnaissance tant méritée illumine votre chemin. Une grande nouvelle confirme que vos espoirs les plus chers se réalisent enfin. Vous portez fièrement la couronne de l'espoir, vainqueur admiré de tous.",
            reversed: "Le doute s'insinue dans votre cœur et la lutte intérieure ternit vos victoires. L'appréhension et la peur de la trahison retardent indéfiniment votre avancée. La déloyauté rôde, semant l'incertitude là où devrait régner la confiance.",
            love: "Votre amour est reconnu et célébré, vous portant ensemble vers des sommets de bonheur partagé.",
            career: "Le succès professionnel éclate au grand jour et vos pairs saluent vos accomplissements avec admiration.",
            spiritual: "Sortez de la chrysalide et laissez votre lumière intérieure rayonner avec créativité et expansion.",
            general: "La victoire sourit à ceux qui ont persévéré, et votre heure de gloire est enfin venue.",
            image: "Wands06",
            element: "🔥 Feu",
            numerology: "Expansion, créativité, sortie de la chrysalide"),

        // Sept de Bâtons
        makeMinor(7, "Sept de Bâtons",
            suit: .wands,
            keywords: ["défense", "bravoure", "persévérance"],
            upright: "Vous tenez votre position avec bravoure, debout au sommet malgré les assauts du monde. Les discussions et négociations exigent de vous une détermination sans faille. Cette carte annonce le succès, car celui qui défend sa colline ne peut être vaincu.",
            reversed: "La perplexité et l'embarras troublent votre esprit, semant l'anxiété dans votre cœur. L'indécision vous fragilise alors qu'il faudrait faire confiance à votre instinct. Gardez-vous de laisser le doute éroder la forteresse que vous avez bâtie.",
            love: "Défendez ce qui compte dans votre relation avec courage et conviction, car l'amour mérite que l'on se batte.",
            career: "Vous faites face à la concurrence avec ténacité, et votre position avantageuse vous mènera au succès.",
            spiritual: "Le travail intérieur vous demande de tenir bon face aux tempêtes de l'âme avec une foi inébranlable.",
            general: "Restez debout et gardez confiance en vos forces, car votre position est plus solide que vous ne le croyez.",
            image: "Wands07",
            element: "🔥 Feu",
            numerology: "Travail intérieur"),

        // Huit de Bâtons
        makeMinor(8, "Huit de Bâtons",
            suit: .wands,
            keywords: ["mouvement", "rapidité", "élan"],
            upright: "Tout s'accélère autour de vous dans un élan de mouvement et de changement irrésistible. La vitesse avec laquelle les événements se déploient promet une félicité assurée à l'horizon. Comme les flèches de l'amour, vos aspirations filent droit vers leur cible.",
            reversed: "L'impatience vous consume ou bien la stagnation vous enlise dans une attente frustrante. Les flèches de la jalousie empoisonnent l'atmosphère, provoquant disputes et querelles. Les conflits intérieurs freinent un élan qui devrait être libre et joyeux.",
            love: "L'amour arrive à grande vitesse, porté par des flèches passionnées qui ne manquent jamais leur cible.",
            career: "Les projets avancent à un rythme effréné, et chaque action porte rapidement ses fruits.",
            spiritual: "La transformation est en marche et le mouvement de l'univers vous emporte vers votre destinée.",
            general: "Les choses se mettent en place avec une rapidité étonnante, laissez-vous porter par ce courant favorable.",
            image: "Wands08",
            element: "🔥 Feu",
            numerology: "Transformation, mouvement"),

        // Neuf de Bâtons
        makeMinor(9, "Neuf de Bâtons",
            suit: .wands,
            keywords: ["résilience", "persistance", "endurance"],
            upright: "Malgré les épreuves, votre résilience vous maintient debout avec une force admirable. Face à l'opposition, vous répondez avec audace et détermination, prêt à tout affronter. Chaque blessure passée est devenue une armure qui vous rend plus fort.",
            reversed: "L'épuisement gagne du terrain et la frustration menace de vous faire plier sous le poids des obstacles. L'adversité semble insurmontable, et les calamités s'accumulent sans répit. Accordez-vous le repos nécessaire avant que vos forces ne vous abandonnent.",
            love: "Votre amour a traversé des tempêtes, et cette endurance partagée renforce les liens du cœur.",
            career: "La persévérance au travail finira par payer, même si le chemin semble encore long et ardu.",
            spiritual: "Intégrez les enseignements tirés de chaque épreuve pour en faire la sagesse qui vous guide.",
            general: "Vous avez survécu à tant de batailles que cette dernière épreuve ne saurait vous abattre.",
            image: "Wands09",
            element: "🔥 Feu",
            numerology: "Intégration des enseignements tirés des autres numéros"),

        // Dix de Bâtons
        makeMinor(10, "Dix de Bâtons",
            suit: .wands,
            keywords: ["fardeau", "responsabilité", "achèvement"],
            upright: "Vous portez un fardeau considérable, mêlant le poids du succès à celui des obligations qui l'accompagnent. Il est temps d'apprendre ce qu'il faut garder et ce dont il faut se défaire avec sagesse. Sous le déguisement de la fortune se cache parfois une oppression silencieuse.",
            reversed: "Le moment est venu de lâcher prise ou de vous demander pourquoi vous vous accrochez si fort. Les contrariétés et les intrigues alourdissent un quotidien déjà pesant. Libérez-vous des fardeaux qui ne vous appartiennent pas pour retrouver votre souffle.",
            love: "Le poids des responsabilités partagées demande à être allégé par un dialogue sincère et aimant.",
            career: "Vos succès professionnels s'accompagnent de charges lourdes qu'il est sage de déléguer ou de reposer.",
            spiritual: "L'achèvement d'un cycle vous invite à déposer vos fardeaux pour renaître plus léger.",
            general: "Discernez l'essentiel du superflu et libérez vos épaules du poids qui n'est plus le vôtre.",
            image: "Wands10",
            element: "🔥 Feu",
            numerology: "Achèvement"),

        // Valet de Bâtons
        makeMinor(11, "Valet de Bâtons",
            suit: .wands,
            keywords: ["exploration", "enthousiasme", "messager"],
            upright: "Un souffle d'enthousiasme et de curiosité vous pousse à explorer des chemins encore inconnus. Tel un jeune messager fidèle, vous portez en vous des nouvelles favorables et un témoignage lumineux. L'énergie de la découverte embrase votre esprit d'une flamme juvénile et sincère.",
            reversed: "La procrastination et l'indécision freinent l'élan d'un cœur pourtant avide d'aventure. De mauvaises nouvelles ou des annonces décevantes sèment l'instabilité autour de vous. L'hésitation vous empêche de saisir les opportunités qui se présentent avec générosité.",
            love: "Un amour jeune et passionné se manifeste, porteur de messages tendres et d'aventures à deux.",
            career: "De nouvelles opportunités professionnelles s'annoncent avec un enthousiasme contagieux et porteur.",
            spiritual: "Enracinez-vous dans vos fondations spirituelles pour mieux explorer les territoires de l'âme.",
            general: "Laissez votre curiosité naturelle vous guider vers de nouvelles aventures pleines de promesses.",
            image: "Wands11",
            element: "🔥 Feu",
            numerology: "Racines/Fondations"),

        // Cavalier de Bâtons
        makeMinor(12, "Cavalier de Bâtons",
            suit: .wands,
            keywords: ["mouvement", "aventure", "passion"],
            upright: "Un mouvement créatif et passionné vous emporte vers de nouvelles destinations avec fougue. Le départ est imminent, qu'il s'agisse d'un voyage, d'une émigration ou d'un changement de vie audacieux. L'énergie du feu galope en vous, impatiente de conquérir de nouveaux horizons.",
            reversed: "L'hésitation freine votre course ou bien la précipitation vous fait brûler les étapes dangereusement. La rupture et la discorde perturbent un voyage qui s'annonçait pourtant lumineux. Trouvez l'équilibre entre l'immobilité stérile et l'emportement aveugle.",
            love: "Une aventure amoureuse passionnée se profile, portée par un élan irrésistible et fougueux.",
            career: "Un changement professionnel dynamique s'annonce, vous propulsant vers de nouvelles conquêtes.",
            spiritual: "Le mouvement est votre prière, chaque pas vous rapproche de votre vérité la plus profonde.",
            general: "Chevauchez la flamme de votre passion et laissez-la vous porter vers l'aventure qui vous appelle.",
            image: "Wands12",
            element: "🔥 Feu",
            numerology: "Mouvement"),

        // Reine de Bâtons
        makeMinor(13, "Reine de Bâtons",
            suit: .wands,
            keywords: ["confiance", "charisme", "magie"],
            upright: "La magie et la confiance rayonnent de tout votre être, attirant à vous le succès et l'admiration. Chaleureuse et honorable, vous incarnez une force aimante qui inspire le respect et la loyauté. Votre charisme naturel transforme chaque entreprise en une réussite éclatante.",
            reversed: "L'incertitude voile votre magie intérieure et vous fait douter de vos pouvoirs véritables. L'opposition et la jalousie empoisonnent des relations qui devraient être nourricières et bienveillantes. La tromperie et l'infidélité menacent un royaume que vous avez bâti avec amour.",
            love: "Votre magnétisme amoureux est irrésistible, et votre confiance illumine la relation de sa chaleur.",
            career: "Votre leadership naturel et votre charisme vous mènent vers le succès dans les affaires avec grâce.",
            spiritual: "Reconnectez-vous à votre magie intérieure et laissez votre flamme sacrée guider votre chemin.",
            general: "Embrassez votre pouvoir avec confiance et bienveillance, car votre lumière est un don pour le monde.",
            image: "Wands13",
            element: "🔥 Feu",
            numerology: "Travail Intérieur"),

        // Roi de Bâtons
        makeMinor(14, "Roi de Bâtons",
            suit: .wands,
            keywords: ["leadership", "vision", "innovation"],
            upright: "Visionnaire et innovant, vous guidez les autres avec un leadership naturel et bienveillant. Honnête et consciencieux, vous incarnez la noblesse du feu qui éclaire sans consumer. Un héritage inattendu ou une récompense méritée couronne votre parcours exemplaire.",
            reversed: "La résistance à diriger vous prive de votre destinée, ou bien l'autoritarisme étouffe ceux qui vous entourent. Bon mais sévère, austère mais tolérant, vous cherchez l'équilibre entre force et douceur. Apprenez à manier le sceptre du pouvoir avec sagesse plutôt qu'avec rigidité.",
            love: "Votre amour est noble et protecteur, offrant à l'être aimé un foyer ardent et une vision partagée.",
            career: "Votre leadership visionnaire inspire vos collaborateurs et ouvre la voie à des réalisations remarquables.",
            spiritual: "La concrétisation de votre parcours spirituel passe par l'incarnation de vos valeurs les plus hautes.",
            general: "Régnez sur votre vie avec la sagesse du feu maîtrisé, alliant vision et action dans chaque décision.",
            image: "Wands14",
            element: "🔥 Feu",
            numerology: "Concrétisation"),
    ]

    // MARK: - Épées (Swords) — 🌬 Air (14 cards)

    static let swordsCards: [TarotCard] = [
// As d'Épées
        makeMinor(1, "As d'Épées",
            suit: .swords,
            keywords: ["Triomphe", "Conquête", "Clarté"],
            upright: "L'As d'Épées annonce un triomphe éclatant de l'esprit, une force mentale qui tranche à travers l'illusion. C'est l'invitation à saisir vos outils intérieurs et à initier un nouveau cycle avec courage et détermination. Une puissance immense se révèle, aussi bien dans l'amour que dans la volonté.",
            reversed: "Un brouillard mental obscurcit votre jugement et peut mener à des résultats désastreux. La confusion s'installe là où la clarté régnait, multipliant les faux départs et les malentendus. Prenez le temps de dissiper cette brume avant d'agir.",
            love: "Une percée intellectuelle ravive la flamme et ouvre un dialogue sincère avec l'être aimé.",
            career: "Votre esprit vif vous propulse vers une victoire professionnelle décisive.",
            spiritual: "L'épée de la vérité coupe les voiles de l'ignorance et vous rapproche de votre essence.",
            general: "Un élan de clarté mentale vous offre la force d'initier un changement majeur dans votre vie.",
            image: "Swords01",
            element: "🌬 Air",
            numerology: "Une invitation à prendre vos outils"),

        // Deux d'Épées
        makeMinor(2, "Deux d'Épées",
            suit: .swords,
            keywords: ["Choix", "Équilibre", "Méditation"],
            upright: "Le Deux d'Épées vous invite à une méditation profonde face à un choix délicat entre deux voies. L'équilibre fragile que vous maintenez témoigne d'un courage intérieur et d'une quête d'harmonie. Laissez la tendresse et l'intimité guider votre cœur vers la bonne direction.",
            reversed: "Vous cherchez à l'extérieur des réponses qui ne peuvent naître qu'en vous. L'imposture et la duplicité brouillent les pistes, rendant tout choix hasardeux. Revenez à votre centre pour démêler le vrai du faux.",
            love: "Un choix amoureux se présente, et seul le silence intérieur vous révélera la voie du cœur.",
            career: "Une décision professionnelle exige de peser chaque option avec soin et discernement.",
            spiritual: "L'équilibre entre la raison et l'intuition vous ouvre les portes d'une sagesse plus profonde.",
            general: "Face à un carrefour, la méditation et le courage intérieur vous permettront de trouver l'harmonie.",
            image: "Swords02",
            element: "🌬 Air",
            numerology: "Dualité, Intuition"),

        // Trois d'Épées
        makeMinor(3, "Trois d'Épées",
            suit: .swords,
            keywords: ["Blessure", "Rupture", "Chagrin"],
            upright: "Le Trois d'Épées révèle des blessures profondes, tant mentales qu'émotionnelles, qui traversent le cœur. La séparation, la rupture et la division laissent des traces douloureuses mais nécessaires à la croissance. Accueillez cette souffrance comme un passage vers une compréhension plus vaste.",
            reversed: "Le temps de la guérison est venu, et chaque blessure devient une source de sagesse. Toutefois, prenez garde à ne pas vous perdre dans la confusion ou la distraction. Soignez vos plaies avec patience et douceur pour retrouver votre unité intérieure.",
            love: "Une peine de cœur profonde demande à être traversée avec compassion pour mieux renaître.",
            career: "Une séparation ou un conflit professionnel, bien que douloureux, ouvre la voie à un nouveau départ.",
            spiritual: "La souffrance connecte l'esprit, l'âme et le corps dans une synthèse transformatrice.",
            general: "Les blessures que vous traversez, aussi profondes soient-elles, portent en elles les graines de la guérison.",
            image: "Swords03",
            element: "🌬 Air",
            numerology: "Synthèse, connexion de l'esprit, de l'âme et du corps"),

        // Quatre d'Épées
        makeMinor(4, "Quatre d'Épées",
            suit: .swords,
            keywords: ["Repos", "Retraite", "Restauration"],
            upright: "Le Quatre d'Épées vous appelle à la retraite et au repos sacré de l'ermite. Votre esprit a besoin de solitude et de silence pour se restaurer pleinement. Accordez-vous ce temps de vigilance intérieure, loin du tumulte du monde.",
            reversed: "Le répit que vous recherchez reste fragile, et l'épuisement menace si vous ne prenez pas soin de vous. Une gestion sage de vos ressources et une prudence accrue sont de mise. Apprenez à poser des limites pour préserver votre énergie vitale.",
            love: "Un temps de retrait permet de retrouver la paix intérieure nécessaire à un amour équilibré.",
            career: "Une pause stratégique dans votre parcours professionnel vous permettra de revenir plus fort.",
            spiritual: "La solitude contemplative restaure votre âme et affine votre connexion au divin.",
            general: "Le repos n'est pas une faiblesse mais une sagesse qui prépare votre prochaine renaissance.",
            image: "Swords04",
            element: "🌬 Air",
            numerology: "Structure, limites, soins personnels"),

        // Cinq d'Épées
        makeMinor(5, "Cinq d'Épées",
            suit: .swords,
            keywords: ["Défaite", "Conflit", "Déshonneur"],
            upright: "Le Cinq d'Épées annonce une période de dégradation et de perte où l'honneur est mis à rude épreuve. La destruction et l'infamie rôdent, laissant un goût amer de défaite dans leur sillage. Acceptez cette traversée sombre comme une étape nécessaire de votre transformation.",
            reversed: "Vous émergez enfin de l'isolement, libéré du poids du ressentiment qui vous enchaînait. Les deuils anciens trouvent leur résolution et laissent place à un renouveau fragile. Permettez-vous de tourner la page avec dignité et compassion.",
            love: "Un conflit douloureux enseigne que la victoire à tout prix en amour n'est jamais une vraie victoire.",
            career: "Une défaite professionnelle, bien qu'humiliante, porte en elle les leçons de l'humilité.",
            spiritual: "L'obscurité de la chrysalide est une étape sacrée de la transformation intérieure.",
            general: "La perte et le déshonneur, aussi douloureux soient-ils, préparent le terrain d'une profonde métamorphose.",
            image: "Swords05",
            element: "🌬 Air",
            numerology: "Chrysalide, l'obscurité comme partie de la transformation"),

        // Six d'Épées
        makeMinor(6, "Six d'Épées",
            suit: .swords,
            keywords: ["Transition", "Voyage", "Passage"],
            upright: "Le Six d'Épées annonce une transition nécessaire, un voyage vers des eaux plus calmes. Vous quittez une rive troublée pour un horizon plus serein, porté par le courant du changement. Ce passage, bien que mélancolique, vous mène vers un avenir plus lumineux.",
            reversed: "Vous transportez avec vous des bagages émotionnels qui alourdissent votre traversée. Des vérités demandent à être exprimées, des confessions à être faites pour alléger votre cœur. Libérez-vous de ce poids pour que le voyage puisse véritablement commencer.",
            love: "Une transition dans votre vie sentimentale vous guide vers des eaux plus paisibles et un amour renouvelé.",
            career: "Un changement de cap professionnel, bien que déstabilisant, vous conduit vers de meilleures opportunités.",
            spiritual: "Vous sortez de la chrysalide, et votre âme déploie ses ailes vers une nouvelle expansion créative.",
            general: "Le voyage que vous entreprenez vous éloigne des turbulences pour vous rapprocher de la sérénité.",
            image: "Swords06",
            element: "🌬 Air",
            numerology: "Expansion, créativité, sortie de la chrysalide"),

        // Sept d'Épées
        makeMinor(7, "Sept d'Épées",
            suit: .swords,
            keywords: ["Ruse", "Incertitude", "Stratégie"],
            upright: "Le Sept d'Épées révèle un conflit intérieur nourri par l'envie et l'incertitude. Des desseins secrets se trament, des plans fragiles qui pourraient bien échouer sous le poids de la duplicité. Examinez vos intentions avec honnêteté avant de poursuivre sur cette voie.",
            reversed: "La clarté revient après une période de doute, et la confiance en soi se restaure doucement. Les bons conseils remplacent les querelles, et l'instruction éclaire ce qui était obscur. Accueillez cette lucidité retrouvée comme un cadeau précieux.",
            love: "Un manque de transparence en amour sème le doute et appelle à plus d'honnêteté dans vos échanges.",
            career: "Une stratégie professionnelle risquée nécessite d'être repensée avec plus de droiture.",
            spiritual: "Le travail intérieur vous invite à examiner vos motivations les plus profondes avec sincérité.",
            general: "L'incertitude et les plans cachés vous rappellent que seule l'honnêteté mène à un succès durable.",
            image: "Swords07",
            element: "🌬 Air",
            numerology: "Travail intérieur"),

        // Huit d'Épées
        makeMinor(8, "Huit d'Épées",
            suit: .swords,
            keywords: ["Piège", "Restriction", "Impuissance"],
            upright: "Le Huit d'Épées décrit le sentiment d'être piégé, entravé par des liens que l'on croit indestructibles. Les mauvaises nouvelles, le chagrin et la censure semblent vous encercler de toutes parts. Pourtant, ces chaînes sont souvent celles de l'esprit, et la liberté commence par un changement de regard.",
            reversed: "Une issue se dessine enfin là où tout semblait bloqué, et les entraves commencent à se desserrer. Malgré les difficultés et les oppositions persistantes, le mouvement reprend son cours. La fatalité que vous redoutiez n'était qu'une illusion qui se dissipe lentement.",
            love: "Un sentiment d'enfermement amoureux vous invite à examiner quelles peurs vous retiennent prisonnier.",
            career: "Des restrictions professionnelles étouffantes cachent en réalité des portes que vous n'avez pas encore vues.",
            spiritual: "La transformation passe par la prise de conscience que vos chaînes sont forgées par vos propres pensées.",
            general: "Vous vous sentez piégé, mais les barrières qui vous entourent sont moins solides qu'elles n'y paraissent.",
            image: "Swords08",
            element: "🌬 Air",
            numerology: "Transformation, mouvement"),

        // Neuf d'Épées
        makeMinor(9, "Neuf d'Épées",
            suit: .swords,
            keywords: ["Anxiété", "Cauchemar", "Désespoir"],
            upright: "Le Neuf d'Épées incarne les nuits blanches hantées par la peur, l'inquiétude et l'anxiété profonde. Le désespoir et la déception semblent écraser votre âme sous leur poids accablant. Pourtant, ces tourments nocturnes sont souvent plus sombres que la réalité du jour qui se lève.",
            reversed: "La libération de la peur s'amorce doucement, comme l'aube après la plus longue des nuits. Les suspicions et les doutes qui vous emprisonnaient commencent à perdre leur emprise. Laissez la honte se dissoudre dans la lumière de la compassion envers vous-même.",
            love: "Les angoisses nocturnes autour de votre vie amoureuse appellent la douceur et le réconfort intérieur.",
            career: "L'anxiété professionnelle qui vous accable est souvent plus grande que le danger réel qui vous menace.",
            spiritual: "L'intégration des épreuves passées transforme vos peurs en sagesse et vos larmes en lumière.",
            general: "Les cauchemars qui vous tourmentent perdent leur pouvoir dès que vous osez les regarder en face.",
            image: "Swords09",
            element: "🌬 Air",
            numerology: "Intégration des enseignements tirés des autres numéros"),

        // Dix d'Épées
        makeMinor(10, "Dix d'Épées",
            suit: .swords,
            keywords: ["Fin", "Effondrement", "Renouveau"],
            upright: "Le Dix d'Épées marque une fin douloureuse, un effondrement qui laisse l'âme emplie de tristesse et de désolation. Les larmes coulent, l'affliction est profonde, mais cette carte n'est pas un arrêt de mort. C'est l'achèvement nécessaire d'un cycle qui ne pouvait plus durer.",
            reversed: "Un soulagement bienvenu succède à la dépression, et les premiers rayons de lumière percent enfin l'obscurité. Des avantages et des succès se profilent, même s'ils restent fragiles et temporaires. Accueillez ce répit avec gratitude, car il annonce un renouveau en devenir.",
            love: "Une fin douloureuse en amour ouvre paradoxalement la porte à un recommencement plus authentique.",
            career: "L'effondrement d'une situation professionnelle libère l'espace nécessaire à une reconstruction plus solide.",
            spiritual: "L'achèvement d'un cycle douloureux marque le seuil sacré d'une renaissance spirituelle.",
            general: "Quand tout semble perdu, rappellez-vous que chaque fin porte en elle la promesse d'un nouveau commencement.",
            image: "Swords10",
            element: "🌬 Air",
            numerology: "Achèvement"),

        // Valet d'Épées
        makeMinor(11, "Valet d'Épées",
            suit: .swords,
            keywords: ["Curiosité", "Vigilance", "Communication"],
            upright: "Le Valet d'Épées apporte un souffle vif d'activité mentale et de communication aiguisée. Son esprit curieux et vigilant observe le monde avec la précision d'un jeune enquêteur avide de vérité. Il vous invite à examiner chaque situation avec attention et discernement.",
            reversed: "La communication se brise, laissant place à la confusion et aux malentendus imprévus. L'esprit, privé de préparation, se retrouve vulnérable face à l'inattendu. Prenez le temps de rétablir les fondations de votre pensée avant de parler ou d'agir.",
            love: "Un échange sincère et curieux avec l'être aimé ravive l'étincelle de la complicité intellectuelle.",
            career: "Votre esprit d'observation et votre vigilance vous ouvrent de nouvelles perspectives professionnelles.",
            spiritual: "Les racines de votre quête spirituelle s'ancrent dans une curiosité vive et une attention éveillée.",
            general: "L'esprit vif et observateur du Valet vous rappelle que la vérité se révèle à ceux qui savent regarder.",
            image: "Swords11",
            element: "🌬 Air",
            numerology: "Racines/Fondations"),

        // Cavalier d'Épées
        makeMinor(12, "Cavalier d'Épées",
            suit: .swords,
            keywords: ["Action", "Ambition", "Bravoure"],
            upright: "Le Cavalier d'Épées charge avec une détermination farouche, porté par une ambition qui ne connaît aucun obstacle. Son habileté et sa bravoure en font un défenseur redoutable, prêt à affronter tous les défis. Il vous appelle à agir avec décision et à avancer sans hésitation.",
            reversed: "L'élan se brise, et l'imprudence remplace la bravoure dans une charge devenue désordonnée. L'incapacité à mesurer les conséquences mène à l'extravagance et aux erreurs coûteuses. Tempérez votre fougue et retrouvez la maîtrise avant de reprendre votre course.",
            love: "Un élan passionné et décisif en amour demande toutefois de ne pas blesser ceux que vous aimez.",
            career: "Votre ambition et votre capacité d'action vous propulsent vers des conquêtes professionnelles remarquables.",
            spiritual: "Le mouvement de l'âme vous pousse à agir en accord avec vos convictions les plus profondes.",
            general: "L'action décisive et la bravoure sont vos alliées, pourvu qu'elles soient guidées par la sagesse.",
            image: "Swords12",
            element: "🌬 Air",
            numerology: "Mouvement"),

        // Reine d'Épées
        makeMinor(13, "Reine d'Épées",
            suit: .swords,
            keywords: ["Indépendance", "Lucidité", "Limites"],
            upright: "La Reine d'Épées incarne une indépendance forgée dans la douleur et une lucidité née de l'expérience. Elle pose des limites claires, ayant traversé le deuil, la séparation et la privation avec une dignité inébranlable. Sa force réside dans sa capacité à voir la vérité sans détourner le regard.",
            reversed: "La rigidité et la critique acérée remplacent la sage fermeté de la Reine. La pruderie et l'artifice masquent une blessure non guérie qui empoisonne les relations. Adoucissez votre regard pour retrouver la noblesse de votre discernement.",
            love: "Des limites saines en amour témoignent d'un respect profond envers vous-même et envers l'autre.",
            career: "Votre indépendance d'esprit et votre lucidité font de vous une autorité respectée dans votre domaine.",
            spiritual: "Le travail intérieur de la Reine vous enseigne que la vraie force naît de l'acceptation de la douleur.",
            general: "La clarté d'esprit et l'indépendance que vous cultivez sont des trésors forgés par les épreuves de la vie.",
            image: "Swords13",
            element: "🌬 Air",
            numerology: "Travail Intérieur"),

        // Roi d'Épées
        makeMinor(14, "Roi d'Épées",
            suit: .swords,
            keywords: ["Autorité", "Vérité", "Jugement"],
            upright: "Le Roi d'Épées s'exprime avec la clarté tranchante de celui qui porte la vérité comme un étendard. Son jugement est sûr, son autorité naturelle, et son intelligence pénètre au cœur de chaque situation. Il vous invite à dire votre vérité avec droiture et à exercer votre pouvoir avec sagesse.",
            reversed: "L'autorité dévoyée se transforme en manipulation, et l'intelligence sert des intentions perverses. La cruauté et la perfidie remplacent la justice et la droiture du souverain. Prenez garde à ne pas laisser le pouvoir corrompre la noblesse de votre esprit.",
            love: "Une communication claire et honnête est la clé d'un amour fondé sur le respect et la vérité.",
            career: "Votre capacité à juger avec discernement et à commander avec autorité vous élève dans votre vie professionnelle.",
            spiritual: "La concrétisation de votre quête spirituelle passe par l'expression authentique de votre vérité intérieure.",
            general: "Le pouvoir véritable réside dans la capacité à dire la vérité avec courage et à agir avec intégrité.",
            image: "Swords14",
            element: "🌬 Air",
            numerology: "Concrétisation"),
    ]

    // MARK: - Deniers (Pentacles) — 🌱 Terre (14 cards)

    static let pentaclesCards: [TarotCard] = [
// As de Deniers
        makeMinor(1, "As de Deniers",
            suit: .pentacles,
            keywords: ["Manifestation", "Opportunité", "Prospérité"],
            upright: "De nouvelles opportunités se manifestent dans votre vie avec une clarté lumineuse. Le contentement et la félicité vous enveloppent, portés par une intelligence vive et une énergie dorée. C'est le moment de saisir ce qui s'offre à vous avec confiance.",
            reversed: "Vous passez peut-être à côté d'opportunités précieuses qui se trouvent juste devant vous. Le mauvais côté de la richesse vous guette, où l'intelligence se détourne de sa noblesse. Même dans l'abondance apparente, quelque chose sonne creux.",
            love: "Une belle opportunité de construire un amour solide et nourrissant se présente à vous.",
            career: "Un nouveau départ professionnel prometteur s'annonce, riche de potentiel concret.",
            spiritual: "Votre âme vous invite à prendre vos outils intérieurs et à bâtir avec intention.",
            general: "Le terreau est fertile : plantez vos graines d'abondance avec gratitude et détermination.",
            image: "Pents01",
            element: "🌱 Terre",
            numerology: "Une invitation à prendre vos outils"),

        // Deux de Deniers
        makeMinor(2, "Deux de Deniers",
            suit: .pentacles,
            keywords: ["Équilibre", "Adaptabilité", "Jonglerie"],
            upright: "La vie vous demande de jongler avec grâce entre plusieurs engagements. Gaieté et récréation se mêlent aux nouvelles qui affluent, créant un tourbillon d'énergie. Votre adaptabilité est votre plus grande force en cette période de mouvement.",
            reversed: "Le déséquilibre vous submerge et vous vous sentez débordé par les sollicitations. La gaieté que vous affichez semble forcée, le plaisir simulé. Il est temps de poser certaines balles au sol pour retrouver votre centre.",
            love: "L'équilibre entre donner et recevoir dans votre vie amoureuse demande toute votre attention.",
            career: "Vous jonglez entre plusieurs projets professionnels avec agilité, mais restez vigilant.",
            spiritual: "La dualité vous enseigne que l'intuition est votre boussole dans le mouvement perpétuel.",
            general: "Accueillez le changement avec souplesse, car c'est dans l'adaptation que naît la maîtrise.",
            image: "Pents02",
            element: "🌱 Terre",
            numerology: "Dualité, Intuition"),

        // Trois de Deniers
        makeMinor(3, "Trois de Deniers",
            suit: .pentacles,
            keywords: ["Collaboration", "Maîtrise", "Coopération"],
            upright: "Le travail d'équipe porte ses fruits et votre savoir-faire est reconnu. Métier, compétence et noblesse d'esprit s'unissent dans une œuvre commune. La renommée et la gloire naissent de cette coopération inspirée.",
            reversed: "Vous tentez de tout accomplir seul, refusant l'aide pourtant précieuse d'autrui. La médiocrité et la mesquinerie guettent ceux qui s'isolent dans leur orgueil. Ouvrez-vous à la sagesse collective pour dépasser vos limites.",
            love: "L'amour se construit à deux, comme une cathédrale où chaque pierre compte.",
            career: "La collaboration professionnelle et le travail qualifié vous mènent vers la reconnaissance.",
            spiritual: "L'esprit, l'âme et le corps trouvent leur synthèse dans l'œuvre partagée avec autrui.",
            general: "Unissez vos talents à ceux des autres pour bâtir quelque chose de véritablement grand.",
            image: "Pents03",
            element: "🌱 Terre",
            numerology: "Synthèse, connexion de l'esprit, de l'âme et du corps"),

        // Quatre de Deniers
        makeMinor(4, "Quatre de Deniers",
            suit: .pentacles,
            keywords: ["Stabilité", "Sécurité", "Conservation"],
            upright: "Un profond sentiment de sécurité matérielle vous enveloppe de sa douceur rassurante. Vos biens sont protégés et l'attachement à ce que vous possédez témoigne de votre sagesse. Les dons, legs et héritages circulent avec bienveillance.",
            reversed: "L'avidité et la possessivité resserrent leur emprise sur votre cœur. Le suspense et les retards vous confrontent à une opposition inattendue. Relâchez votre prise pour laisser l'abondance circuler librement.",
            love: "La stabilité affective vous offre un refuge sûr où l'amour peut s'épanouir sereinement.",
            career: "Vos ressources professionnelles sont bien gérées et votre position est solidement ancrée.",
            spiritual: "Prenez soin de vous-même en posant des limites saines qui structurent votre monde intérieur.",
            general: "La vraie sécurité naît non pas de ce que l'on retient, mais de ce que l'on sait protéger avec amour.",
            image: "Pents04",
            element: "🌱 Terre",
            numerology: "Structure, limites, soins personnels"),

        // Cinq de Deniers
        makeMinor(5, "Cinq de Deniers",
            suit: .pentacles,
            keywords: ["Pénurie", "Épreuve", "Résilience"],
            upright: "L'esprit de pénurie assombrit votre regard sur le monde et les ennuis matériels pèsent lourd. Pourtant, même dans la misère, cette carte murmure aussi d'amour et d'affinités profondes. Les épreuves révèlent les liens véritables qui vous soutiennent.",
            reversed: "Vous commencez enfin à sortir de la pénurie, mais le chemin reste fragile. Le désordre, le chaos et la discorde ont laissé leurs traces sur votre passage. Cessez la prodigalité pour reconstruire sur des bases plus solides.",
            love: "Même dans les moments difficiles, l'amour véritable se révèle comme un phare dans la nuit.",
            career: "Les difficultés financières actuelles sont temporaires et portent en elles les graines du renouveau.",
            spiritual: "L'obscurité fait partie de la transformation, comme la chrysalide prépare le papillon.",
            general: "Traversez cette épreuve avec courage, car la lumière perce toujours au bout du tunnel.",
            image: "Pents05",
            element: "🌱 Terre",
            numerology: "Chrysalide, l'obscurité comme partie de la transformation"),

        // Six de Deniers
        makeMinor(6, "Six de Deniers",
            suit: .pentacles,
            keywords: ["Générosité", "Partage", "Gratification"],
            upright: "Le flux sacré du donner et du recevoir s'écoule harmonieusement dans votre vie. Présents, cadeaux et gratifications témoignent d'une attention vigilante envers autrui. La prospérité actuelle vous invite à partager vos richesses avec grâce.",
            reversed: "Les dettes s'accumulent et le désir de posséder obscurcit votre jugement. La cupidité, l'envie et la jalousie tissent un voile d'illusion sur vos yeux. Retrouvez l'équilibre entre ce que vous donnez et ce que vous retenez.",
            love: "La générosité du cœur nourrit votre relation d'une lumière chaleureuse et réconfortante.",
            career: "Votre générosité professionnelle est remarquée et la prospérité circule vers vous naturellement.",
            spiritual: "En sortant de votre chrysalide, votre créativité s'épanouit dans le partage avec le monde.",
            general: "Donnez avec le cœur ouvert, car l'univers rend au centuple ce qui est offert avec sincérité.",
            image: "Pents06",
            element: "🌱 Terre",
            numerology: "Expansion, créativité, sortie de la chrysalide"),

        // Sept de Deniers
        makeMinor(7, "Sept de Deniers",
            suit: .pentacles,
            keywords: ["Patience", "Persévérance", "Évaluation"],
            upright: "La patience et la persévérance sont vos alliées les plus fidèles en cette période. Les affaires et les échanges demandent du temps pour mûrir, comme un fruit sur sa branche. Votre ingéniosité et votre innocence vous guideront à travers les altercations passagères.",
            reversed: "L'impatience et la fébrilité rongent votre sérénité face aux résultats qui tardent. Des motifs d'inquiétude concernant l'argent troublent votre sommeil et votre paix. Rappelez-vous que les plus belles récoltes demandent les soins les plus attentifs.",
            love: "La patience est la clé qui ouvre les portes d'un amour profond et durable.",
            career: "Vos efforts professionnels portent leurs fruits lentement mais sûrement, continuez avec constance.",
            spiritual: "Le travail intérieur demande la même patience que le jardinier accorde à ses semences.",
            general: "Contemplez le chemin parcouru avec fierté et laissez le temps accomplir son œuvre silencieuse.",
            image: "Pents07",
            element: "🌱 Terre",
            numerology: "Travail intérieur"),

        // Huit de Deniers
        makeMinor(8, "Huit de Deniers",
            suit: .pentacles,
            keywords: ["Apprentissage", "Artisanat", "Dévouement"],
            upright: "Le travail acharné et l'apprentissage façonnent votre avenir avec une précision d'artisan. Emploi, commission et compétence artisanale s'entrelacent dans un stade préparatoire prometteur. Chaque geste répété avec amour vous rapproche de la maîtrise véritable.",
            reversed: "Le perfectionnisme vous paralyse tandis que la négligence guette dans l'ombre. L'ambition déçue engendre la vanité et la cupidité, détournant votre esprit ingénieux vers la ruse. Retrouvez la joie simple de l'apprentissage sans vous perdre dans l'excès.",
            love: "L'amour, comme l'artisanat, se polit jour après jour avec patience et dévouement.",
            career: "Votre engagement dans l'apprentissage et le perfectionnement de vos compétences porte ses fruits.",
            spiritual: "La transformation s'opère dans le mouvement patient de vos mains qui façonnent votre destinée.",
            general: "Consacrez-vous à votre art avec humilité, car la maîtrise naît de la répétition amoureuse.",
            image: "Pents08",
            element: "🌱 Terre",
            numerology: "Transformation, mouvement"),

        // Neuf de Deniers
        makeMinor(9, "Neuf de Deniers",
            suit: .pentacles,
            keywords: ["Abondance", "Gratitude", "Accomplissement"],
            upright: "L'abondance et la gratitude illuminent votre vie comme un jardin en pleine floraison. La prudence et le discernement vous ont mené vers la sécurité et l'accomplissement. Savourez cette récolte bien méritée avec un cœur plein de certitude sereine.",
            reversed: "Un sentiment de pénurie persiste malgré les apparences d'abondance autour de vous. L'escroquerie, la tromperie et la mauvaise foi menacent vos projets les plus chers. Restez vigilant et ne laissez personne ternir le fruit de vos efforts.",
            love: "Votre cœur récolte enfin les doux fruits d'un amour cultivé avec soin et discernement.",
            career: "La réussite professionnelle vous sourit, couronnant des années de travail et de prudence.",
            spiritual: "Vous intégrez avec sagesse les enseignements tirés de chaque étape de votre parcours sacré.",
            general: "L'abondance véritable se goûte dans la gratitude pour chaque bénédiction, grande ou petite.",
            image: "Pents09",
            element: "🌱 Terre",
            numerology: "Intégration des enseignements tirés des autres numéros"),

        // Dix de Deniers
        makeMinor(10, "Dix de Deniers",
            suit: .pentacles,
            keywords: ["Héritage", "Famille", "Pérennité"],
            upright: "L'héritage et la sécurité vous entourent d'une aura de plénitude familiale. Gain, richesse et affaires domestiques s'entremêlent dans la demeure chaleureuse de votre lignée. Les archives de votre histoire personnelle racontent une saga d'abondance partagée.",
            reversed: "L'insatisfaction à l'égard de vos réalisations vous empêche de voir la richesse qui vous entoure. Le hasard, la fatalité et les jeux de chance menacent ce qui a été patiemment construit. Protégez votre héritage des pertes inutiles et des risques inconsidérés.",
            love: "L'amour se tisse dans la trame familiale, créant un héritage de tendresse pour les générations futures.",
            career: "La prospérité professionnelle s'inscrit dans la durée et bénéficie à tout votre entourage.",
            spiritual: "L'achèvement d'un cycle vous invite à contempler la richesse de tout ce que vous avez bâti.",
            general: "La vraie richesse se mesure aux liens que vous tissez et à l'héritage lumineux que vous transmettez.",
            image: "Pents10",
            element: "🌱 Terre",
            numerology: "Achèvement"),

        // Valet de Deniers
        makeMinor(11, "Valet de Deniers",
            suit: .pentacles,
            keywords: ["Étude", "Curiosité", "Potentiel"],
            upright: "De nouvelles idées et opportunités émergent, vous connectant à vos ressources intérieures les plus profondes. L'application, l'étude et l'érudition ouvrent des portes insoupçonnées devant vous. Les messages et nouvelles qui arrivent portent en eux les germes d'un avenir radieux.",
            reversed: "Votre concentration vacille et les distractions vous éloignent de vos objectifs essentiels. La prodigalité et la dissipation gaspillent vos précieuses ressources dans le luxe éphémère. Des nouvelles défavorables vous invitent à recentrer votre attention sur l'essentiel.",
            love: "Un souffle nouveau d'émerveillement et de curiosité vient rafraîchir votre vie affective.",
            career: "L'étude et l'application ouvrent des portes professionnelles prometteuses et enrichissantes.",
            spiritual: "Vos racines spirituelles s'enfoncent plus profondément, fondant votre croissance sur un sol fertile.",
            general: "Accueillez les nouvelles idées avec l'enthousiasme d'un éternel apprenti au cœur ouvert.",
            image: "Pents11",
            element: "🌱 Terre",
            numerology: "Racines/Fondations"),

        // Cavalier de Deniers
        makeMinor(12, "Cavalier de Deniers",
            suit: .pentacles,
            keywords: ["Méthode", "Responsabilité", "Fiabilité"],
            upright: "Votre esprit méthodique et organisé trace un chemin sûr vers la réalisation de vos ambitions. L'utilité, la serviabilité et la rectitude guident chacun de vos pas avec une assurance tranquille. Votre sens de la responsabilité inspire confiance à tous ceux qui vous entourent.",
            reversed: "L'éparpillement vous gagne et l'inertie s'installe dans votre quotidien comme une brume tenace. L'oisiveté, la stagnation et le découragement étouffent votre élan naturel. Retrouvez votre sens de l'engagement pour sortir de cette placidité insouciante.",
            love: "Votre fiabilité et votre dévouement offrent à l'être aimé un amour solide comme le roc.",
            career: "Votre méthode et votre sens des responsabilités vous rendent indispensable dans votre domaine.",
            spiritual: "Le mouvement vers la sagesse demande la même discipline que le cavalier accorde à sa monture.",
            general: "Avancez avec constance et méthode, car la persévérance régulière accomplit des merveilles.",
            image: "Pents12",
            element: "🌱 Terre",
            numerology: "Mouvement"),

        // Reine de Deniers
        makeMinor(13, "Reine de Deniers",
            suit: .pentacles,
            keywords: ["Abondance", "Bienveillance", "Nourriture"],
            upright: "Les soins personnels, la créativité et l'abondance rayonnent de tout votre être avec magnificence. L'opulence et la générosité coulent de source, offrant sécurité et liberté à ceux que vous chérissez. Vous incarnez la terre nourricière dans toute sa splendeur bienveillante.",
            reversed: "Votre être tout entier réclame des soins et de l'attention que vous lui refusez depuis trop longtemps. Le mal, la suspicion et la peur s'insinuent là où la méfiance a remplacé la confiance. Tournez votre générosité légendaire vers vous-même pour guérir en profondeur.",
            love: "Votre amour généreux et nourrissant crée un jardin d'Éden où les cœurs s'épanouissent.",
            career: "Votre créativité et votre sens de l'abondance attirent la prospérité naturellement vers vous.",
            spiritual: "Le travail intérieur de soin de soi est la source sacrée d'où jaillit toute vraie abondance.",
            general: "Prenez soin de vous avec la même tendresse que vous offrez si généreusement aux autres.",
            image: "Pents13",
            element: "🌱 Terre",
            numerology: "Travail Intérieur"),

        // Roi de Deniers
        makeMinor(14, "Roi de Deniers",
            suit: .pentacles,
            keywords: ["Prospérité", "Maîtrise", "Générosité"],
            upright: "La prospérité et la générosité couronnent votre parcours d'une lumière souveraine. Votre vaillance et votre intelligence réalisatrice témoignent d'une aptitude remarquable aux affaires. Le succès que vous connaissez est le fruit mûr d'une sagesse longuement cultivée.",
            reversed: "La mauvaise gestion des ressources et l'entêtement ébranlent les fondations de votre royaume. Le vice, la faiblesse et la corruption menacent ce que vous avez bâti avec tant d'efforts. Il est temps de retrouver l'intégrité qui fait la noblesse du véritable souverain.",
            love: "Votre amour stable et prospère offre un foyer où chacun se sent roi en son cœur.",
            career: "Votre maîtrise des affaires et votre intelligence pratique vous placent au sommet de votre art.",
            spiritual: "La concrétisation de votre chemin spirituel se manifeste dans la sagesse de vos actes quotidiens.",
            general: "Régnez sur votre vie avec la générosité d'un roi sage qui sait que la vraie richesse se partage.",
            image: "Pents14",
            element: "🌱 Terre",
            numerology: "Concrétisation"),
    ]


    // MARK: - Helpers

    private static func makeMajor(
        _ number: Int,
        _ name: String,
        _ keywords: [String],
        _ upright: String,
        _ reversed: String,
        love: String,
        career: String,
        spiritual: String,
        general: String = "",
        image: String,
        element: String = "",
        numerology: String = "",
        description: String = ""
    ) -> TarotCard {
        TarotCard(
            number: number,
            name: name,
            arcana: .major,
            keywords: keywords,
            uprightMeaning: upright,
            reversedMeaning: reversed,
            interpretation: TarotCard.Interpretation(
                general: general.isEmpty ? "\(name) t'invite à te réaligner avec ta vérité intérieure." : general,
                love: love,
                career: career,
                spiritual: spiritual
            ),
            imageName: image,
            element: element,
            numerology: numerology,
            cardDescription: description
        )
    }

    private static func makeMinor(
        _ number: Int,
        _ name: String,
        suit: TarotCard.Arcana,
        keywords: [String],
        upright: String,
        reversed: String,
        love: String,
        career: String,
        spiritual: String,
        general: String = "",
        image: String,
        element: String = "",
        numerology: String = "",
        description: String = ""
    ) -> TarotCard {
        TarotCard(
            number: number,
            name: name,
            arcana: suit,
            keywords: keywords,
            uprightMeaning: upright,
            reversedMeaning: reversed,
            interpretation: TarotCard.Interpretation(
                general: general.isEmpty ? "\(name) t'invite à harmoniser ton quotidien avec ton intention." : general,
                love: love,
                career: career,
                spiritual: spiritual
            ),
            imageName: image,
            element: element,
            numerology: numerology,
            cardDescription: description
        )
    }
}
